export interface Recipient {
    slug: string
    name: string
    type: 1 | 2 // Bali, BDC
}

const recipients: Recipient[] = [
    { name: 'Steven', slug: 'steven', type: 1 },
    { name: 'Sheilly & Ricky', slug: 'sheilly-ricky', type: 1 },
    { name: 'Arif & Jessy', slug: 'arif-jessy', type: 1 },
    { name: 'Michael & Dorothy', slug: 'michael-dorothy', type: 1 },
    { name: 'Moses', slug: 'moses', type: 1 },
    { name: 'Elvina & Julian', slug: 'elvina-julian', type: 1 },
    { name: 'Christ Billy', slug: 'christ-billy', type: 1 },
    { name: 'Hendy & Rima', slug: 'hendy-rima', type: 1 },
    { name: 'Jevon & Melissa', slug: 'jevon-melissa', type: 1 },
    { name: 'Juan & Maria', slug: 'juan-maria', type: 1 },
    { name: 'Priscil & Albi', slug: 'priscil-albi', type: 1 },
    { name: 'Christy & Albert', slug: 'christy-albert', type: 1 },
    { name: 'Jeanny', slug: 'jeanny', type: 1 },
    { name: 'Evan', slug: 'evan', type: 1 },
    { name: 'Dennis & Caroline', slug: 'dennis-caroline', type: 1 },
    { name: 'Suk Eko & Ai Marta', slug: 'suk-eko-ai-marta', type: 1 },
    { name: 'Marcel & Jennie', slug: 'marcel-jennie', type: 1 },
    { name: 'Devena', slug: 'devena', type: 1 },
    { name: 'Martha & Steven', slug: 'martha-steven', type: 1 },
    { name: 'Judith & Thijs', slug: 'judith-thijs', type: 1 },
    { name: 'Anna & Thomas', slug: 'anna-thomas', type: 1 },
    { name: 'Deo & Ellya', slug: 'deo-ellya', type: 1 },
    { name: 'Hans & Shella', slug: 'hans-shella', type: 1 },
    { name: 'Dees', slug: 'dees', type: 1 },
    { name: 'Ivana', slug: 'ivana', type: 1 },
    { name: 'Dipta & Avi', slug: 'dipta-avi', type: 1 },
    { name: 'Kenny', slug: 'kenny', type: 1 },
    { name: 'Jackie', slug: 'jackie', type: 1 },
    { name: 'Nicholas & Beatrice', slug: 'nicholas-beatrice', type: 1 },
    { name: 'Bagas & Vania', slug: 'bagas-vania', type: 1 },
    { name: 'Jessica & Darren', slug: 'jessica-darren', type: 1 },
    { name: 'Venny & Ruben', slug: 'venny-ruben', type: 1 },
    { name: 'Romi & Joost', slug: 'romi-joost', type: 1 },
    { name: 'Sonja', slug: 'sonja', type: 1 },
    { name: 'Jennifer', slug: 'jennifer', type: 1 },
    { name: 'Olivia Irena', slug: 'olivia-irena', type: 1 },
    { name: 'Ciciliya & Carlson', slug: 'ciciliya-carlson', type: 1 },
    { name: 'Abed', slug: 'abed', type: 1 },
    { name: 'Erni & Nico', slug: 'erni-nico', type: 1 },
    { name: 'Ryan Santoso', slug: 'ryan-santoso', type: 1 },
    { name: 'Meichael', slug: 'meichael', type: 1 },
    { name: 'Tara & Rio', slug: 'tara-rio', type: 1 },
    { name: 'Mutia & Mami', slug: 'mutia-mami', type: 1 },
    { name: 'Natasha & Rony', slug: 'natasha-rony', type: 1 },
    { name: 'Alvin Sugianto', slug: 'alvin-sugianto', type: 1 },
    { name: 'Alex & Frilin', slug: 'alex-frilin', type: 1 },
    { name: 'Ron', slug: 'ron', type: 1 },
    { name: 'Travis', slug: 'travis', type: 1 },
    { name: 'Risa', slug: 'risa', type: 1 },
    { name: 'Shania', slug: 'shania', type: 1 },
    { name: 'Herman', slug: 'herman', type: 1 },
    { name: 'Alvian', slug: 'alvian', type: 1 },
    { name: 'Belinda', slug: 'belinda', type: 1 },
    { name: 'Afa', slug: 'afa', type: 1 },
    { name: 'Hansen', slug: 'hansen', type: 1 },
    { name: 'Michael Lauw', slug: 'michael-lauw', type: 1 },
    { name: 'Felianty', slug: 'felianty', type: 1 },
    { name: 'Citra & Ryu', slug: 'citra-ryu', type: 1 },
    { name: 'Ruben', slug: 'ruben', type: 1 },
    { name: 'Azza & Waseem', slug: 'azza-waseem', type: 1 },
    { name: 'Saed & Jeannie', slug: 'saed-jeannie', type: 1 },
    { name: 'Prisca & Thobi', slug: 'prisca-thobi', type: 1 },
    { name: 'Adi', slug: 'adi', type: 1 },
    { name: 'Kayleen', slug: 'kayleen', type: 1 },
    { name: 'Nathania & Andre', slug: 'nathania-andre', type: 1 },
    { name: 'Julian', slug: 'julian', type: 1 },
    { name: 'Saviour & Dara', slug: 'saviour-dara', type: 1 },
    { name: 'Mama', slug: 'mama', type: 1 },
    { name: 'Ko Nico', slug: 'ko-nico', type: 1 },
    { name: 'Lena Hartatik', slug: 'lena-hartatik', type: 1 },
    { name: 'Heri & Siska', slug: 'heri-siska', type: 1 },
    { name: 'Nio Bertha Katriani', slug: 'nio-bertha-katriani', type: 1 },
    { name: 'Benny & Yuanita', slug: 'benny-yuanita', type: 1 },
    { name: 'Haricipto & Mutiara Rosemary', slug: 'haricipto-mutiara-rosemary', type: 1 },
    { name: 'Jiu Abun & Jiu Mu', slug: 'jiu-abun-jiu-mu', type: 1 },
    { name: 'Tuaku & Tuakim', slug: 'tuaku-tuakim', type: 1 },
    { name: 'Jiku & Jikim', slug: 'jiku-jikim', type: 1 },
    { name: 'Suk Canon & Ii Ayen', slug: 'suk-canon-ii-ayen', type: 1 },
    { name: 'Saku Awie', slug: 'saku-awie', type: 1 },
    { name: 'Itio Asui & Ii Acien', slug: 'itio-asui-ii-acien', type: 1 },
    { name: 'Clarissa & Chelsea', slug: 'clarissa-chelsea', type: 1 },
    { name: 'Sa Lau Kou', slug: 'sa-lau-kou', type: 1 },
    { name: 'Maya Banjarmasin', slug: 'maya-banjarmasin', type: 1 },
    { name: 'Mr. & Mrs. Tse Tat Ming', slug: 'mr-mrs-tse-tat-ming', type: 1 },
    { name: 'Lau Cu Kou', slug: 'lau-cu-kou', type: 1 },
    { name: 'Suk Minto & Ii Fenny', slug: 'suk-minto-ii-fenny', type: 1 },
    { name: 'Sa Lau Kou & Cek A Ui', slug: 'sa-lau-kou-cek-a-ui', type: 1 },
    { name: 'Tua Lau Kim & Ling', slug: 'tua-lau-kim-ling', type: 1 },
    { name: 'Sa Lau Ku & Sa Lau Kiem', slug: 'sa-lau-ku-sa-lau-kiem', type: 1 },
    { name: 'Papa & Mama', slug: 'papa-mama', type: 1 },
    { name: 'Metta', slug: 'metta', type: 1 },
    { name: 'Ama', slug: 'ama', type: 1 },
    { name: 'Jicek & Jisim', slug: 'jicek-jisim', type: 1 },
    { name: 'Tuakou & Tuatio', slug: 'tuakou-tuatio', type: 1 },
    { name: 'Maria', slug: 'maria', type: 1 },
    { name: 'Dea', slug: 'dea', type: 1 },

    { name: 'Y.A. Viriyanadi Mahathera', slug: 'bhante-viriyanadi', type: 2 },
    { name: 'Y.A. Nyana Vijjananda Mahathera', slug: 'bhante-vijjananda', type: 2 },
    { name: 'Y.A. Nyana Dharmamaitri Mahathera', slug: 'bhante-dharmamaitri', type: 2 },
    { name: 'Y.A. Nyanasila Thera', slug: 'bhante-nyanasila', type: 2 },
    { name: 'Y.A. Vangisa Deva Thera', slug: 'bhante-vangisa', type: 2 },
    { name: 'Y.A. Nyanaloka Stavira', slug: 'bhante-loka', type: 2 },
    { name: 'Samanera Kristianto Batuadji', slug: 'samanera-kris', type: 2 },
]

export function getRecipient(slug: string): Recipient | undefined {
    return recipients.find(r => r.slug === slug)
}

export const recipientInjectionKey = Symbol('recipient') as InjectionKey<Recipient | undefined>
