export interface Recipient {
    slug: string
    name: string
    type: 1 | 2 // Bali, BDC
}

const recipients: Recipient[] = [
    { name: 'Steven', slug: 'steven', type: 1 },
    { name: 'Axel', slug: 'axel-himawan', type: 1 },
    { name: 'Sheilly & Ricky', slug: 'sheilly-ricky', type: 1 },
    { name: 'Arif & Jessy', slug: 'arif-jessy', type: 1 },
    { name: 'Amelia Tan', slug: 'amelia-tan', type: 1 },
    { name: 'Michael & Dorothy', slug: 'michael-dorothy', type: 1 },
    { name: 'Moses', slug: 'moses', type: 1 },
    { name: 'Elvina & Julian', slug: 'elvina-julian', type: 1 },
    { name: 'Christ Billy', slug: 'christ-billy', type: 1 },
    { name: 'Hendy & Rima', slug: 'hendy-rima', type: 1 },
    { name: 'Jevon & Melissa', slug: 'jevon-melissa', type: 1 },
    { name: 'Juan & Maria', slug: 'juan-maria', type: 1 },
    { name: 'Priscil & Albi', slug: 'priscil-albi', type: 1 },
    { name: 'Christy & Albert', slug: 'christy-albert', type: 1 },
    { name: 'Jeanny', slug: 'jeanny', type: 1 },
    { name: 'Evan', slug: 'evan', type: 1 },
    { name: 'Dennis & Caroline', slug: 'dennis-caroline', type: 1 },
    { name: 'Suk Eko & Ai Marta', slug: 'suk-eko-ai-marta', type: 1 },
    { name: 'Marcel & Jennie', slug: 'marcel-jennie', type: 1 },
    { name: 'Devena', slug: 'devena', type: 1 },
    { name: 'Martha & Steven', slug: 'martha-steven', type: 1 },
    { name: 'Judith & Thijs', slug: 'judith-thijs', type: 1 },
    { name: 'Anne & Thomas', slug: 'anne-thomas', type: 1 },
    { name: 'Deo & Ellya', slug: 'deo-ellya', type: 1 },
    { name: 'Hans & Shella', slug: 'hans-shella', type: 1 },
    { name: 'Dees', slug: 'dees', type: 1 },
    { name: 'Ivana', slug: 'ivana', type: 1 },
    { name: 'Dipta & Avi', slug: 'dipta-avi', type: 1 },
    { name: 'Kenny', slug: 'kenny', type: 1 },
    { name: 'Jackie', slug: 'jackie', type: 1 },
    { name: 'Nicholas & Beatrice', slug: 'nicholas-beatrice', type: 1 },
    { name: 'Bagas & Vania', slug: 'bagas-vania', type: 1 },
    { name: 'Jessica & Darren', slug: 'jessica-darren', type: 1 },
    { name: 'Venny & Ruben', slug: 'venny-ruben', type: 1 },
    { name: 'Romi & Joost', slug: 'romi-joost', type: 1 },
    { name: 'Sonja', slug: 'sonja', type: 1 },
    { name: 'Jennifer', slug: 'jennifer', type: 1 },
    { name: 'Olivia Irena', slug: 'olivia-irena', type: 1 },
    { name: 'Ciciliya & Carlson', slug: 'ciciliya-carlson', type: 1 },
    { name: 'Abed', slug: 'abed', type: 1 },
    { name: 'Erni & Nico', slug: 'erni-nico', type: 1 },
    { name: 'Ryan Santoso', slug: 'ryan-santoso', type: 1 },
    { name: 'Meichael', slug: 'meichael', type: 1 },
    { name: 'Tara & Rio', slug: 'tara-rio', type: 1 },
    { name: 'Mutia & Mami Edith', slug: 'mutia-mami', type: 1 },
    { name: 'Natasha & Rony', slug: 'natasha-rony', type: 1 },
    { name: 'Alvin Sugianto', slug: 'alvin-sugianto', type: 1 },
    { name: 'Alex & Frilin', slug: 'alex-frilin', type: 1 },
    { name: 'Ron', slug: 'ron', type: 1 },
    { name: 'Travis', slug: 'travis', type: 1 },
    { name: 'Risa', slug: 'risa', type: 1 },
    { name: 'Shania', slug: 'shania', type: 1 },
    { name: 'Herman', slug: 'herman', type: 1 },
    { name: 'Alvian', slug: 'alvian', type: 1 },
    { name: 'Belinda', slug: 'belinda', type: 1 },
    { name: 'Afa', slug: 'afa', type: 1 },
    { name: 'Hansen', slug: 'hansen', type: 1 },
    { name: 'Michael Lauw', slug: 'michael-lauw', type: 1 },
    { name: 'Felianty', slug: 'felianty', type: 1 },
    { name: 'Citra & Ryu', slug: 'citra-ryu', type: 1 },
    { name: 'Ruben', slug: 'ruben', type: 1 },
    { name: 'Azza & Waseem', slug: 'azza-waseem', type: 1 },
    { name: 'Saed & Jeannie', slug: 'saed-jeannie', type: 1 },
    { name: 'Prisca & Thobi', slug: 'prisca-thobi', type: 1 },
    { name: 'Adi', slug: 'adi', type: 1 },
    { name: 'Kayleen', slug: 'kayleen', type: 1 },
    { name: 'Nathania & Andre', slug: 'nathania-andre', type: 1 },
    { name: 'Julian', slug: 'julian', type: 1 },
    { name: 'Saviour & Dara', slug: 'saviour-dara', type: 1 },
    { name: 'Mama', slug: 'mama', type: 1 },
    { name: 'Ko Nico', slug: 'ko-nico', type: 1 },
    { name: 'Lena Hartatik', slug: 'lena-hartatik', type: 1 },
    { name: 'Heri & Siska', slug: 'heri-siska', type: 1 },
    { name: 'Nio Bertha Katriani', slug: 'nio-bertha-katriani', type: 1 },
    { name: 'Benny & Yuanita', slug: 'benny-yuanita', type: 1 },
    { name: 'Haricipto & Mutiara Rosemary', slug: 'haricipto-mutiara-rosemary', type: 1 },
    { name: 'Galih & Retno', slug: 'galih-retno', type: 1 },
    { name: 'Hendra & Choriah', slug: 'hendra-chroriah', type: 1 },
    { name: 'Jiu Abun & Jiu Mu', slug: 'jiu-abun-jiu-mu', type: 1 },
    { name: 'Tuaku & Tuakim', slug: 'tuaku-tuakim', type: 1 },
    { name: 'Jiku & Jikim', slug: 'jiku-jikim', type: 1 },
    { name: 'Suk Canon & Ii Ayen', slug: 'suk-canon-ii-ayen', type: 1 },
    { name: 'Saku Awie', slug: 'saku-awie', type: 1 },
    { name: 'Itio Asui & Ii Acien', slug: 'itio-asui-ii-acien', type: 1 },
    { name: 'Clarissa & Chelsea', slug: 'clarissa-chelsea', type: 1 },
    { name: 'Sa Lau Kou', slug: 'sa-lau-kou', type: 1 },
    { name: 'Maya Banjarmasin', slug: 'maya-banjarmasin', type: 1 },
    { name: 'Mr. & Mrs. Tse Tat Ming', slug: 'mr-mrs-tse-tat-ming', type: 1 },
    { name: 'Lau Cu Kou', slug: 'lau-cu-kou', type: 1 },
    { name: 'Suk Minto & Ii Fenny', slug: 'suk-minto-ii-fenny', type: 1 },
    { name: 'Sa Lau Kou & Cek A Ui', slug: 'sa-lau-kou-cek-a-ui', type: 1 },
    { name: 'Tua Lau Kim & Ling', slug: 'tua-lau-kim-ling', type: 1 },
    { name: 'Sa Lau Ku & Sa Lau Kiem', slug: 'sa-lau-ku-sa-lau-kiem', type: 1 },
    { name: 'Papa & Mama', slug: 'papa-mama', type: 1 },
    { name: 'Metta', slug: 'metta', type: 1 },
    { name: 'Ama', slug: 'ama', type: 1 },
    { name: 'Jicek & Jisim', slug: 'jicek-jisim', type: 1 },
    { name: 'Tuakou & Tuatio', slug: 'tuakou-tuatio', type: 1 },
    { name: 'Maria', slug: 'maria', type: 1 },
    { name: 'Dea', slug: 'dea', type: 1 },
    { name: 'Cimone Kraucamp', slug: 'cimone', type: 1 },
    { name: 'Clara', slug: 'clara', type: 1 },
    { name: 'Aldi', slug: 'aldi', type: 1 },
    { name: 'Kezia & Rei', slug: 'kezia-rei', type: 1 },
    { name: 'Carlson', slug: 'carlson', type: 1 },
    { name: 'Vivy & Adit', slug: 'vivy-adit', type: 1 },
    { name: 'Chindra', slug: 'chindra', type: 1 },
    { name: 'Melinda Tanudirjo', slug: 'melinda-tan', type: 1 },
    { name: 'Gaby Cherilyn', slug: 'gaby-cherilyn', type: 1 },
    { name: 'Clarissa Djimantoro', slug: 'clarissa-djimantoro', type: 1 },
    { name: 'Ruth Hadinjoto', slug: 'ruth-hadinjoto', type: 1 },
    { name: 'Ricky & Avi', slug: 'ricky-avi', type: 1 },
    { name: 'Benhard', slug: 'benhard', type: 1 },
    { name: 'Calvin Tantio', slug: 'calvin-tantio', type: 1 },

    { name: 'Y.A. Viriyanadi Mahathera', slug: 'bhante-viriyanadi', type: 2 },
    { name: 'Y.A. Nyana Vijjananda Mahathera', slug: 'bhante-vijjananda', type: 2 },
    { name: 'Y.A. Nyana Dharmamaitri Mahathera', slug: 'bhante-dharmamaitri', type: 2 },
    { name: 'Y.A. Nyanasila Thera', slug: 'bhante-nyanasila', type: 2 },
    { name: 'Y.A. Vangisa Deva Thera', slug: 'bhante-vangisa', type: 2 },
    { name: 'Y.A. Nyanaloka Stavira', slug: 'bhante-loka', type: 2 },
    { name: 'Samanera Kristianto Batuadji', slug: 'samanera-kris', type: 2 },

    { name: 'Mr. & Mrs. Rudy Budiman', slug: 'rudy-budiman', type: 2 },
    { name: 'Mr. & Mrs. Sanjaya Kangginandhi', slug: 'sanjaya-kangginandhi', type: 2 },
    { name: 'Mr. & Mrs. Gde Sidharta Putra', slug: 'gde-sidharta-putra', type: 2 },
    { name: 'Mr. & Mrs. Hudy Suharto', slug: 'hudy-suharto', type: 2 },
    { name: 'Mr. & Mrs. Fredrik Ong', slug: 'fredrik-ong', type: 2 },
    { name: 'Mr. & Mrs. Amin Tanjung', slug: 'amin-tanjung', type: 2 },
    { name: 'Mr. & Mrs. Tjandra', slug: 'tjandra', type: 2 },
    { name: 'Mr. & Mrs. Soerjadi Tjiotijono', slug: 'soerjadi-tjiotijono', type: 2 },
    { name: 'Mr. & Mrs. Wira Santoso', slug: 'wira-santoso', type: 2 },
    { name: 'Ms Rivanna', slug: 'rivanna', type: 2 },
    { name: 'Mr. Heindra & Mrs. Suzan Ardianti', slug: 'heindra-suzan-ardianti', type: 2 },
    { name: 'Mr. & Mrs. Eman Dipapapraja', slug: 'eman-dipapapraja', type: 2 },
    { name: 'Mr. & Mrs. Herman Saputra', slug: 'herman-saputra', type: 2 },
    { name: 'Mr. & Mrs. Wahjudi Gatot', slug: 'wahjudi-gatot', type: 2 },
    { name: 'Mr. & Mrs. Yongki Pranoto', slug: 'yongki-pranoto', type: 2 },
    { name: 'Mr. & Mrs. Kusno Sugeng', slug: 'kusno-sugeng', type: 2 },
    { name: 'Mr. & Mrs. Prof Sujoko Efferin', slug: 'sujoko-efferin', type: 2 },
    { name: 'Mr. & Mrs. Tosin', slug: 'tosin', type: 2 },
    { name: 'Mr. & Mrs. Paychun Limansaputra', slug: 'paychun-limansaputra', type: 2 },
    { name: 'Mr. & Mrs. Erick Angkasa', slug: 'erick-angkasa', type: 2 },
    { name: 'Mr. & Mrs. Haryanto Tanuwijaya', slug: 'haryanto-tanuwijaya', type: 2 },
    { name: 'Mr. Yulianto & Mrs. Dewi', slug: 'yulianto-dewi', type: 2 },
    { name: 'Mr. Wiranto & Mrs. Marylyn', slug: 'wiranto-marylyn', type: 2 },
    { name: 'Ms. Jenny Lukito', slug: 'jenny-lukito', type: 2 },
    { name: 'Ms. Lina Tailuan', slug: 'lina-tailuan', type: 2 },
    { name: 'Lau Ku Budi & Akow Aily', slug: 'lau-ku-budi-akow-aily', type: 2 },
    { name: 'Mr. & Mrs. Ing Wibisono', slug: 'ing-wibisono', type: 2 },
    { name: 'Mr. & Mrs. Irwan Pontoh', slug: 'irwan-pontoh', type: 2 },
    { name: 'Ms. Murni (Achu)', slug: 'murni', type: 2 },
    { name: 'Mr. & Mrs. Amri', slug: 'amri', type: 2 },
    { name: 'Mr. & Mrs. Koh Yan Suwandi', slug: 'koh-yan-suwandi', type: 2 },
    { name: 'Mr. Herry & Mrs. Suhernanik', slug: 'herry-suhernanik', type: 2 },
    { name: 'Mr. Acai & Ms. Diana Loekmini', slug: 'acai-diana-loekmini', type: 2 },
    { name: 'Mr. Wijaya & Mrs. Dewi Loek', slug: 'wijaya-dewi-loek', type: 2 },
    { name: 'Ms. Henny Chandra', slug: 'henny-chandra', type: 2 },
    { name: 'Mr. Edy Minarto & Mrs. Lily Margaretha', slug: 'edy-minarto-lily-margaretha', type: 2 },
    { name: 'Ms. Nanik Lim', slug: 'nanik-lim', type: 2 },
    { name: 'Ms. Amei (Ng Mui Keng)', slug: 'amei', type: 2 },
    { name: 'Mr. Chen Chong & Mrs. Devi', slug: 'chen-chong-devi', type: 2 },
    { name: 'Ms. Kiem Fon (Bunga)', slug: 'kiem-fon', type: 2 },
    { name: 'Mr. Rudy Kwok & Ms. Mei Fang', slug: 'rudy-kwok-mei-fang', type: 2 },
    { name: 'Mr. Lilik Setiaji & Mrs. Wiwik Wijayati', slug: 'lilik-setiaji-wiwik-wijayati', type: 2 },
    { name: 'Ms. Siska & mama', slug: 'siska-mama', type: 2 },
    { name: 'Ms. Yang Yang', slug: 'yang-yang', type: 2 },
    { name: 'Mr. & Mrs. Yanto Muliawan', slug: 'yanto-muliawan', type: 2 },
    { name: 'Mr. Peter & Mrs. Mega', slug: 'peter-mega', type: 2 },
    { name: 'Mr. Mulyanto Widjaja & Mrs. Anira', slug: 'mulyanto-widjaja-anira', type: 2 },
    { name: 'Mr. Willy Suryajaya & Ms. Endang', slug: 'willy-suryajaya-endang', type: 2 },
    { name: 'Ms. Etty', slug: 'etty', type: 2 },
    { name: 'Mr. Yohnny Wiyono & Mrs. Rita Phuasanto', slug: 'yohnny-wiyono-rita-phuasanto', type: 2 },
    { name: 'Romo Abaya & ibu Partinem', slug: 'abaya-partinem', type: 2 },
    { name: 'Romo Agung Prajna Mudita', slug: 'agung-prajna-mudita', type: 2 },
    { name: 'Ms. Go Giok Cu', slug: 'go-giok-cu', type: 2 },
    { name: 'Ms. Aylan', slug: 'aylan', type: 2 },
    { name: 'Ms. Ong Kinta Dewi', slug: 'ong-kinta-dewi', type: 2 },
    { name: 'Ms. Herlena Chandra', slug: 'herlena-chandra', type: 2 },
    { name: 'Ms. Chen Chen', slug: 'chen-chen', type: 2 },
    { name: 'Ms. Ong Paramithasari', slug: 'ong-paramithasari', type: 2 },
    { name: 'Ms. Hu Aida Futmawati', slug: 'hu-aida-futmawati', type: 2 },
    { name: 'Mr. Alexan Loe & Ms. Amelia', slug: 'alexan-loe-amelia', type: 2 },
    { name: 'Mr. & Mrs. Sandy Honger', slug: 'sandy-honger', type: 2 },
    { name: 'Mr. Lie Tong San', slug: 'lie-tong-san', type: 2 },
    { name: 'Ms. Linawati Ong + mama Lina', slug: 'linawati-ong-mama-lina', type: 2 },
    { name: 'Ms. Bilistini Halim & family', slug: 'bilistini-halim-family', type: 2 },
    { name: 'Ms. Jeannete (Sianne)', slug: 'jeannete-sianne', type: 2 },
    { name: 'Ms. Suk Mei (Padma Devi)', slug: 'suk-mei-padma-devi', type: 2 },
    { name: 'Mr. Wiyono & Mrs. Tantri', slug: 'wiyono-tantri', type: 2 },
    { name: 'Mr. Ichi & Mrs. Meliana', slug: 'ichi-meliana', type: 2 },
    { name: 'Ms. Susi Surianti', slug: 'susi-surianti', type: 2 },
    { name: 'Ms. Yenny', slug: 'yenny', type: 2 },
    { name: 'Ms. Indra & Mr. Anton', slug: 'indra-anton', type: 2 },
    { name: 'Mr. Eko & Mrs. Emmy + mom\'s', slug: 'eko-emmy', type: 2 },
    { name: 'Mr. & Mrs. Hendro Tjia', slug: 'hendro-tjia', type: 2 },
    { name: 'Mr. & Mrs. Johan', slug: 'johan', type: 2 },
    { name: 'Mr. & Mrs. Seng Sudiono', slug: 'seng-sudiono', type: 2 },
    { name: 'Ms. Nurhayati Seng', slug: 'nurhayati-seng', type: 2 },
    { name: 'Mr. Salimun & Mrs. Julyati Wibowo', slug: 'salimun-julyati-wibowo', type: 2 },
    { name: 'Mr. Santo & Mrs. Ida Bagus Kartika', slug: 'santo-ida-bagus-kartika', type: 2 },
    { name: 'Ms. Juliana Chandra', slug: 'juliana-chandra', type: 2 },
    { name: 'Ms. Nanik Lim', slug: 'nanik-lim', type: 2 },
    { name: 'Ms. Henny Tjio', slug: 'henny-tjio', type: 2 },
    { name: 'Ms. Mei Ming', slug: 'mei-ming', type: 2 },
    { name: 'Ms. Sri Rahayu', slug: 'sri-rahayu', type: 2 },
    { name: 'Ms. Fetty Padmawati', slug: 'fetty-padmawati', type: 2 },
    { name: 'Ms. Sulaniwati', slug: 'sulaniwati', type: 2 },
    { name: 'Mr. & Mrs. Yanuar', slug: 'yanuar', type: 2 },
    { name: 'Mrs. Linda & Ms. Brenda', slug: 'linda-brenda', type: 2 },
    { name: 'Ms. Kemalawati (Wawa)', slug: 'kemalawati-wawa', type: 2 },
    { name: 'Mrs. Cahyo / Elly Tjandraningsih', slug: 'cahyo-elly-tjandraningsih', type: 2 },
    { name: 'Mr. & Mrs. Aditya', slug: 'aditya', type: 2 },
    { name: 'Mr. Sianjito & Mrs. Welly', slug: 'sianjito-welly', type: 2 },
    { name: 'Mr. & Mrs. Pradipta', slug: 'pradipta', type: 2 },
    { name: 'Mr. Agus Sulistio & Mrs. Erika', slug: 'agus-sulistio-erika', type: 2 },
    { name: 'Mr. Budiono & Ms. Ida Budiarti', slug: 'budiono-ida-budiarti', type: 2 },
    { name: 'Mrs. Shanti', slug: 'shanti', type: 2 },
    { name: 'Mrs. Sutini Tjokro', slug: 'sutini-tjokro', type: 2 },
    { name: 'Ms. Milda', slug: 'milda', type: 2 },
    { name: 'Mr & Ms. Tisna', slug: 'tisna', type: 2 },
    { name: 'Mr. Suwandi', slug: 'suwandi', type: 2 },
    { name: 'Mr. Irwan & Mrs. Yenny', slug: 'irwan-yenny', type: 2 },
    { name: 'Ms. Frida Ferdiana', slug: 'frida-ferdiana', type: 2 },
    { name: 'Mr. Friski Fernando', slug: 'friski-fernando', type: 2 },
    { name: 'Mr. Ahock & Mrs. Ayen', slug: 'ahock-ayen', type: 2 },
    { name: 'Mr. & Mrs. Gimon & Evelyn', slug: 'gimon-evelyn', type: 2 },
    { name: 'Mr. Pongky & Mrs. Win Agatha', slug: 'pongky-win-agatha', type: 2 },
    { name: 'Mrs. Veronika Jap', slug: 'veronika-jap', type: 2 },
    { name: 'Ms. Ninik Sandrawati & Ms. Chindra', slug: 'ninik-sandrawati-chindra', type: 2 },
    { name: 'Mr. & Mrs. Felix Tanudirjo + Ms. Melinda', slug: 'felix-tanudirjo-melinda', type: 2 },
    { name: 'Mr. & Mrs. Eddy Sutikno Djimantoro', slug: 'eddy-sutikno-djimantoro', type: 2 },
    { name: 'Mr. & Mrs. Agustinus + Ms. Ruth', slug: 'agustinus-ruth', type: 2 },
    { name: 'Mr. & Ms. Hendra Tanujaya + Ms. Gaby', slug: 'hendra-tanujaya-gaby', type: 2 },
    { name: 'Mr. & Mrs. Untung Handi Muljanto', slug: 'untung-handi-muljanto', type: 2 },
    { name: 'Mr. & Mrs. Imam Santoso', slug: 'imam-santoso', type: 2 },
    { name: 'Lau Kow Lie Ik Cu', slug: 'lau-kow-lie-ik-cu', type: 2 },
    { name: 'Mr. Dhani Suherwindro', slug: 'dhani-suherwindro', type: 2 },
    { name: 'Mr. Teguh Riyanto', slug: 'teguh-riyanto', type: 2 },
    { name: 'Mr. Nanang', slug: 'nanang', type: 2 },
    { name: 'Ms. Wahyuningsih', slug: 'wahyuningsih', type: 2 },
    { name: 'Ms. Esti Wulandari', slug: 'esti-wulandari', type: 2 },
    { name: 'Mr. & Mrs. Sebastian Hendra (Jicek & Jisiem)', slug: 'sebastian-hendra', type: 2 },
    { name: 'Mr. & Mrs. Eric Priyo Tranggono', slug: 'eric-priyo-tranggono', type: 2 },
    { name: 'Mr. & Mrs. Jonowi', slug: 'jonowi', type: 2 },
    { name: 'Mr. & Mrs. Andy Limanto', slug: 'andy-limanto', type: 2 },
    { name: 'Mr. & Mrs. Ronally', slug: 'ronally', type: 2 },
    { name: 'Mr. & Mrs. Iskandar', slug: 'iskandar', type: 2 },
    { name: 'Mrs. Wenny Lu', slug: 'wenny-lu', type: 2 },
    { name: 'Mr. Frans & Mrs. Alexandra', slug: 'frans-alexandra', type: 2 },
    { name: 'Mr. Tanto & Mrs. Natalia', slug: 'tanto-natalia', type: 2 },
    { name: 'Mr. Hendra & Mrs. Herlin', slug: 'hendra-herlin', type: 2 },
    { name: 'Mr. Kehat & Mrs. Dewi', slug: 'kehat-dewi', type: 2 },
    { name: 'Mrs. Djamilah', slug: 'djamilah', type: 2 },
    { name: 'Mrs. Mei Fang', slug: 'mei-fang', type: 2 },
    { name: 'Mr. Adnan & Mrs. Rita', slug: 'adnan-rita', type: 2 },
    { name: 'Mr. Mulianto', slug: 'mulianto', type: 2 },
    { name: 'Mrs. Allen', slug: 'allen', type: 2 },
    { name: 'Mrs. Yayan', slug: 'yayan', type: 2 },
    { name: 'Ms. Ristin', slug: 'ristin', type: 2 },
    { name: 'Ms. Devi', slug: 'devi', type: 2 },
    { name: 'Ms. Sammy', slug: 'sammy', type: 2 },
    { name: 'Ms. Lia', slug: 'lia', type: 2 },
    { name: 'Ms. Maggie', slug: 'maggie', type: 2 },
    { name: 'Mr. & Mrs. Yudha Buana', slug: 'yudha-buana', type: 2 },
    { name: 'Ms. Fetien', slug: 'fetien', type: 2 },
    { name: 'Mrs. Julia Guizal', slug: 'julia-guizal', type: 2 },
    { name: 'Ms. Sakura', slug: 'sakura', type: 2 },
    { name: 'Mr. & Mrs. Ferry Soedikno (Ji tio & Ji kow)', slug: 'ferry-soedikno', type: 2 },
    { name: 'Mrs. Dyah Puspitasari', slug: 'dyah-puspitasari', type: 2 },
    { name: 'Mrs. Catherine / Ayen', slug: 'catherine-ayen', type: 2 },
    { name: 'Mr. & Mrs. Widyanto', slug: 'widyanto', type: 2 },
    { name: 'Mr. & Mrs. Yulius Usman', slug: 'yulius-usman', type: 2 },
    { name: 'Mr. Wilianto & Mrs. Betty', slug: 'aloek-betty', type: 2 },
    { name: 'Evelyne & Vincent', slug: 'evelyne-vincent', type: 2 },

    { name: 'Mr. & Mrs. Harley Wiyogo', slug: 'harley-wiyogo', type: 2 },
    { name: 'Mr. & Mrs. Ronny Sugianto', slug: 'ronny-sugianto', type: 2 },
    { name: 'Mr. & Mrs. Hadi Suyitno', slug: 'hadi-suyitno', type: 2 },
    { name: 'Mr. & Mrs. Desandito Mulyo', slug: 'desandito-mulyo', type: 2 },
    { name: 'Hendra Dion & partner', slug: 'hendra-dion', type: 2 },
    { name: 'Ce Tri & Ko Mul', slug: 'tri-mul', type: 2 },
    { name: 'Riady Salim', slug: 'riady-salim', type: 2 },
    { name: 'Anthony Guang', slug: 'anthony-guang', type: 2 },
    { name: 'Jhonny & partner', slug: 'jhonny', type: 2 },
    { name: 'Sugiarto & Sukina', slug: 'sugiarto-sukina', type: 2 },
    { name: 'Valen', slug: 'valen', type: 2 },
    { name: 'Ce Dahana', slug: 'ce-dahana', type: 2 },
    { name: 'Ce Meily', slug: 'ce-meily', type: 2 },
    { name: 'Diana & Chiari', slug: 'diana-chiari', type: 2 },
    { name: 'Ronny & Yulen', slug: 'ronny-yulen', type: 2 },
    { name: 'Sasshy', slug: 'sasshy', type: 2 },
    { name: 'Yogie', slug: 'yogie', type: 2 },
    { name: 'Fery & Nina', slug: 'fery-nina', type: 2 },
    { name: 'Julinar & Santoso', slug: 'julinar-santoso', type: 2 },
    { name: 'Gunawan', slug: 'gunawan-setiawan', type: 2 },
    { name: 'Glenn', slug: 'glenn-ferio', type: 2 },
    { name: 'Sanitya', slug: 'sanitya', type: 2 },
    { name: 'Vivi & Kevin', slug: 'vivi-kevin', type: 2 },
    { name: 'Jessica & Hendri', slug: 'jessica-hendri', type: 2 },
]

export function getRecipient(slug: string): Recipient | undefined {
    return recipients.find(r => r.slug === slug)
}

export const recipientInjectionKey = Symbol('recipient') as InjectionKey<Recipient | undefined>
